#!/bin/bash

export TERM=xterm-color

if [ "$SBT_OPTS" == "" ]; then
  export SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled"
fi

if [ -f ./sbt ]; then
  exec ./sbt "$@"
elif [ -x /usr/bin/sbt ]; then
  exec /usr/bin/sbt "$@"
else
  exec java $SBT_OPTS -jar "$HOME/programs/sbt/sbt-launch.jar" "$@"
fi

