#!/bin/bash

export TERM=xterm-color

if [ -f ./sbt ]; then
  exec ./sbt "$@"
else
  if [ "$SBT_OPTS" == "" ]; then
    export SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled"
  fi

  exec java $SBT_OPTS -jar "$HOME/programs/sbt/sbt-launch.jar" "$@"
fi
